name=WitPlusDccEx
version=1.1.27
author=Peter Akers <akersp62@gmail.com>, David Zuhn <zoo@statebeltrailway.org>, Luca Dentella <luca@dentella.it>
maintainer=Peter Akers <akersp62@gmail.com>
sentence=WiThrottle Protocol and DCC-EX Native protocol implementation for ESP32
paragraph=This library implements the WiThrottle protocol (as used in JMRI and other servers) as well as the DCC-EX Native protocol (used by DCC-EX EX-CommandStations), allowing an Ardunio device to connect to the server and act as a client (such as a dedicated fast clock device or a hardware based throttle).
category=Other
url=https://github.com/flash62au/WitPlusDccEx
architectures=*